services:
  - type: web
    name: dopamine-health-recommender
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: "pip install -r requirements.txt && python import_products.py && python train_model.py"
    startCommand: "python app.py"
    autoDeploy: true
